-- i should generate these via code, but for the prototyping stage this was quicker.
-- addendum: well since i had to skip doors and some corners for textures, it'll do.

return {
  { -- TIER 1
    -- top left to top right
    {offset = {-3.5, -3.5}, direction = defines.direction.north, corners = -1},
    {offset = {-2.5, -3.5}, direction = defines.direction.north},
    {offset = {-1.5, -3.5}, direction = defines.direction.north},
    {offset = {-0.5, -3.5}, direction = defines.direction.north},
    {offset = { 0.5, -3.5}, direction = defines.direction.north},
    {offset = { 1.5, -3.5}, direction = defines.direction.north},
    {offset = { 2.5, -3.5}, direction = defines.direction.north},
    {offset = { 3.5, -3.5}, direction = defines.direction.north, corners =  1},

    -- top right to bottom right
    {offset = { 3.5, -3.5}, direction = defines.direction.east , corners = -1},
    {offset = { 3.5, -2.5}, direction = defines.direction.east },
    {offset = { 3.5, -1.5}, direction = defines.direction.east },
    {offset = { 3.5, -0.5}, direction = defines.direction.east },
    {offset = { 3.5,  0.5}, direction = defines.direction.east },
    {offset = { 3.5,  1.5}, direction = defines.direction.east },
    {offset = { 3.5,  2.5}, direction = defines.direction.east },
    {offset = { 3.5,  3.5}, direction = defines.direction.east , corners =  1},

    -- bottom right to bottom left
    {offset = { 3.5,  3.5}, direction = defines.direction.south, corners = -1},
    {offset = { 2.5,  3.5}, direction = defines.direction.south},
    {offset = { 1.5,  3.5}, direction = defines.direction.south},
    -- {offset = { 0.5,  3.5}, direction = defines.direction.south},
    -- {offset = {-0.5,  3.5}, direction = defines.direction.south},
    {offset = {-1.5,  3.5}, direction = defines.direction.south},
    {offset = {-2.5,  3.5}, direction = defines.direction.south},
    {offset = {-3.5,  3.5}, direction = defines.direction.south, corners =  1},

    -- bottom left to top left
    {offset = {-3.5,  3.5}, direction = defines.direction.west , corners = -1},
    {offset = {-3.5,  2.5}, direction = defines.direction.west },
    {offset = {-3.5,  1.5}, direction = defines.direction.west },
    {offset = {-3.5,  0.5}, direction = defines.direction.west },
    {offset = {-3.5, -0.5}, direction = defines.direction.west },
    {offset = {-3.5, -1.5}, direction = defines.direction.west },
    {offset = {-3.5, -2.5}, direction = defines.direction.west },
    {offset = {-3.5, -3.5}, direction = defines.direction.west , corners =  1},
  },
  { -- TIER 2
    -- {offset = {-5.5, -5.5}, direction = defines.direction.north, corners = -1},
    {offset = {-4.5, -5.5}, direction = defines.direction.north},
    {offset = {-3.5, -5.5}, direction = defines.direction.north},
    {offset = {-2.5, -5.5}, direction = defines.direction.north},
    {offset = {-1.5, -5.5}, direction = defines.direction.north},
    {offset = {-0.5, -5.5}, direction = defines.direction.north},
    {offset = { 0.5, -5.5}, direction = defines.direction.north},
    {offset = { 1.5, -5.5}, direction = defines.direction.north},
    {offset = { 2.5, -5.5}, direction = defines.direction.north},
    {offset = { 3.5, -5.5}, direction = defines.direction.north},
    {offset = { 4.5, -5.5}, direction = defines.direction.north},
    -- {offset = { 5.5, -5.5}, direction = defines.direction.north, corners =  1},

    -- {offset = { 5.5, -5.5}, direction = defines.direction.east , corners = -1},
    {offset = { 5.5, -4.5}, direction = defines.direction.east },
    {offset = { 5.5, -3.5}, direction = defines.direction.east },
    {offset = { 5.5, -2.5}, direction = defines.direction.east },
    {offset = { 5.5, -1.5}, direction = defines.direction.east },
    {offset = { 5.5, -0.5}, direction = defines.direction.east },
    {offset = { 5.5,  0.5}, direction = defines.direction.east },
    {offset = { 5.5,  1.5}, direction = defines.direction.east },
    {offset = { 5.5,  2.5}, direction = defines.direction.east },
    {offset = { 5.5,  3.5}, direction = defines.direction.east },
    {offset = { 5.5,  4.5}, direction = defines.direction.east },
    {offset = { 5.5,  5.5}, direction = defines.direction.east , corners =  1},

    {offset = { 5.5,  5.5}, direction = defines.direction.south, corners = -1},
    {offset = { 4.5,  5.5}, direction = defines.direction.south},
    {offset = { 3.5,  5.5}, direction = defines.direction.south},
    {offset = { 2.5,  5.5}, direction = defines.direction.south},
    -- {offset = { 1.5,  5.5}, direction = defines.direction.south},
    -- {offset = { 0.5,  5.5}, direction = defines.direction.south},
    -- {offset = {-0.5,  5.5}, direction = defines.direction.south},
    -- {offset = {-1.5,  5.5}, direction = defines.direction.south},
    {offset = {-2.5,  5.5}, direction = defines.direction.south},
    {offset = {-3.5,  5.5}, direction = defines.direction.south},
    {offset = {-4.5,  5.5}, direction = defines.direction.south},
    {offset = {-5.5,  5.5}, direction = defines.direction.south, corners =  1},

    {offset = {-5.5,  5.5}, direction = defines.direction.west , corners = -1},
    {offset = {-5.5,  4.5}, direction = defines.direction.west },
    {offset = {-5.5,  3.5}, direction = defines.direction.west },
    {offset = {-5.5,  2.5}, direction = defines.direction.west },
    {offset = {-5.5,  1.5}, direction = defines.direction.west },
    {offset = {-5.5,  0.5}, direction = defines.direction.west },
    {offset = {-5.5, -0.5}, direction = defines.direction.west },
    {offset = {-5.5, -1.5}, direction = defines.direction.west },
    {offset = {-5.5, -2.5}, direction = defines.direction.west },
    {offset = {-5.5, -3.5}, direction = defines.direction.west },
    {offset = {-5.5, -4.5}, direction = defines.direction.west },
    -- {offset = {-5.5, -3.5}, direction = defines.direction.west , corners =  1},
  },
  { -- TIER 3
    -- {offset = {-7.5, -7.5}, direction = defines.direction.north, corners = -1},
    -- {offset = {-6.5, -7.5}, direction = defines.direction.north},
    {offset = {-5.5, -7.5}, direction = defines.direction.north},
    {offset = {-4.5, -7.5}, direction = defines.direction.north},
    {offset = {-3.5, -7.5}, direction = defines.direction.north},
    {offset = {-2.5, -7.5}, direction = defines.direction.north},
    -- {offset = {-1.5, -7.5}, direction = defines.direction.north},
    -- {offset = {-0.5, -7.5}, direction = defines.direction.north},
    -- {offset = { 0.5, -7.5}, direction = defines.direction.north},
    -- {offset = { 1.5, -7.5}, direction = defines.direction.north},
    {offset = { 2.5, -7.5}, direction = defines.direction.north},
    {offset = { 3.5, -7.5}, direction = defines.direction.north},
    {offset = { 4.5, -7.5}, direction = defines.direction.north},
    {offset = { 5.5, -7.5}, direction = defines.direction.north},
    -- {offset = { 6.5, -7.5}, direction = defines.direction.north},
    -- {offset = { 7.5, -7.5}, direction = defines.direction.north, corners =  1},

    -- {offset = { 7.5, -7.5}, direction = defines.direction.east , corners = -1},
    {offset = { 7.5, -6.5}, direction = defines.direction.east },
    {offset = { 7.5, -5.5}, direction = defines.direction.east },
    {offset = { 7.5, -4.5}, direction = defines.direction.east },
    {offset = { 7.5, -3.5}, direction = defines.direction.east },
    {offset = { 7.5, -2.5}, direction = defines.direction.east },
    {offset = { 7.5, -1.5}, direction = defines.direction.east },
    {offset = { 7.5, -0.5}, direction = defines.direction.east },
    {offset = { 7.5,  0.5}, direction = defines.direction.east },
    {offset = { 7.5,  1.5}, direction = defines.direction.east },
    {offset = { 7.5,  2.5}, direction = defines.direction.east },
    {offset = { 7.5,  3.5}, direction = defines.direction.east },
    {offset = { 7.5,  4.5}, direction = defines.direction.east },
    {offset = { 7.5,  5.5}, direction = defines.direction.east },
    {offset = { 7.5,  6.5}, direction = defines.direction.east },
    {offset = { 7.5,  7.5}, direction = defines.direction.east , corners =  1},

    {offset = { 7.5,  7.5}, direction = defines.direction.south, corners = -1},
    {offset = { 6.5,  7.5}, direction = defines.direction.south},
    {offset = { 5.5,  7.5}, direction = defines.direction.south},
    {offset = { 4.5,  7.5}, direction = defines.direction.south},
    {offset = { 3.5,  7.5}, direction = defines.direction.south},
    {offset = { 2.5,  7.5}, direction = defines.direction.south},
    -- {offset = { 1.5,  7.5}, direction = defines.direction.south},
    -- {offset = { 0.5,  7.5}, direction = defines.direction.south},
    -- {offset = {-0.5,  7.5}, direction = defines.direction.south},
    -- {offset = {-1.5,  7.5}, direction = defines.direction.south},
    {offset = {-2.5,  7.5}, direction = defines.direction.south},
    {offset = {-3.5,  7.5}, direction = defines.direction.south},
    {offset = {-4.5,  7.5}, direction = defines.direction.south},
    {offset = {-5.5,  7.5}, direction = defines.direction.south},
    {offset = {-6.5,  7.5}, direction = defines.direction.south},
    {offset = {-7.5,  7.5}, direction = defines.direction.south, corners =  1},

    {offset = {-7.5,  7.5}, direction = defines.direction.west , corners = -1},
    {offset = {-7.5,  6.5}, direction = defines.direction.west },
    {offset = {-7.5,  5.5}, direction = defines.direction.west },
    {offset = {-7.5,  4.5}, direction = defines.direction.west },
    {offset = {-7.5,  3.5}, direction = defines.direction.west },
    {offset = {-7.5,  2.5}, direction = defines.direction.west },
    {offset = {-7.5,  1.5}, direction = defines.direction.west },
    {offset = {-7.5,  0.5}, direction = defines.direction.west },
    {offset = {-7.5, -0.5}, direction = defines.direction.west },
    {offset = {-7.5, -1.5}, direction = defines.direction.west },
    {offset = {-7.5, -2.5}, direction = defines.direction.west },
    {offset = {-7.5, -3.5}, direction = defines.direction.west },
    {offset = {-7.5, -4.5}, direction = defines.direction.west },
    {offset = {-7.5, -5.5}, direction = defines.direction.west },
    {offset = {-7.5, -6.5}, direction = defines.direction.west },
    -- {offset = {-7.5, -7.5}, direction = defines.direction.west , corners =  1},
  }
}
