return {
--abstract                   , -- EntityWithOwnerPrototype                
  'accumulator'              , --   AccumulatorPrototype                  
  'artillery-turret'         , --   ArtilleryTurretPrototype              
  'beacon'                   , --   BeaconPrototype                       
  'boiler'                   , --   BoilerPrototype                       
  'burner-generator'         , --   BurnerGeneratorPrototype              
  'character'                , --   CharacterPrototype                    
--abstract                   , --   CombinatorPrototype                   
  'arithmetic-combinator'    , --     ArithmeticCombinatorPrototype       
  'decider-combinator'       , --     DeciderCombinatorPrototype          
  'constant-combinator'      , --   ConstantCombinatorPrototype           
  'container'                , --   ContainerPrototype                    
  'logistic-container'       , --     LogisticContainerPrototype          
  'infinity-container'       , --       InfinityContainerPrototype        
--abstract                   , --   CraftingMachinePrototype              
  'assembling-machine'       , --     AssemblingMachinePrototype          
  'rocket-silo'              , --       RocketSiloPrototype               
  'furnace'                  , --     FurnacePrototype                    
  'electric-energy-interface', --   ElectricEnergyInterfacePrototype      
  'electric-pole'            , --   ElectricPolePrototype                 
  'unit-spawner'             , --   EnemySpawnerPrototype                 
--abstract                   , --   FlyingRobotPrototype                  
  'combat-robot'             , --     CombatRobotPrototype                
--abstract                   , --     RobotWithLogisticInterfacePrototype 
  'construction-robot'       , --       ConstructionRobotPrototype        
  'logistic-robot'           , --       LogisticRobotPrototype            
  'gate'                     , --   GatePrototype                         
  'generator'                , --   GeneratorPrototype                    
  'heat-interface'           , --   HeatInterfacePrototype                
  'heat-pipe'                , --   HeatPipePrototype                     
  'inserter'                 , --   InserterPrototype                     
  'lab'                      , --   LabPrototype                          
  'lamp'                     , --   LampPrototype                         
  'land-mine'                , --   LandMinePrototype                     
  'linked-container'         , --   LinkedContainerPrototype              
  'market'                   , --   MarketPrototype                       
  'mining-drill'             , --   MiningDrillPrototype                  
  'offshore-pump'            , --   OffshorePumpPrototype                 
  'pipe'                     , --   PipePrototype                         
  'infinity-pipe'            , --     InfinityPipePrototype               
  'pipe-to-ground'           , --   PipeToGroundPrototype                 
  'player-port'              , --   PlayerPortPrototype                   
  'power-switch'             , --   PowerSwitchPrototype                  
  'programmable-speaker'     , --   ProgrammableSpeakerPrototype          
  'pump'                     , --   PumpPrototype                         
  'radar'                    , --   RadarPrototype                        
--abstract                   , --   RailPrototype                         
  'curved-rail'              , --     CurvedRailPrototype                 
  'straight-rail'            , --     StraightRailPrototype               
--abstract                   , --   RailSignalBasePrototype               
  'rail-chain-signal'        , --     RailChainSignalPrototype            
  'rail-signal'              , --     RailSignalPrototype                 
  'reactor'                  , --   ReactorPrototype                      
  'roboport'                 , --   RoboportPrototype                     
  'simple-entity-with-owner' , --   SimpleEntityWithOwnerPrototype        
  'simple-entity-with-force' , --     SimpleEntityWithForcePrototype      
  'solar-panel'              , --   SolarPanelPrototype                   
  'storage-tank'             , --   StorageTankPrototype                  
  'train-stop'               , --   TrainStopPrototype                    
--abstract                   , --   TransportBeltConnectablePrototype     
  'linked-belt'              , --     LinkedBeltPrototype                 
--abstract                   , --     LoaderPrototype                     
  'loader-1x1'               , --       Loader1x1Prototype                
  'loader'                   , --       Loader1x2Prototype                
  'splitter'                 , --     SplitterPrototype                   
  'transport-belt'           , --     TransportBeltPrototype              
  'underground-belt'         , --     UndergroundBeltPrototype            
  'turret'                   , --   TurretPrototype                       
  'ammo-turret'              , --     AmmoTurretPrototype                 
  'electric-turret'          , --     ElectricTurretPrototype             
  'fluid-turret'             , --     FluidTurretPrototype                
  'unit'                     , --   UnitPrototype                         
--abstract                   , --   VehiclePrototype                      
  'car'                      , --     CarPrototype                        
--abstract                   , --     RollingStockPrototype               
  'artillery-wagon'          , --       ArtilleryWagonPrototype           
  'cargo-wagon'              , --       CargoWagonPrototype               
  'fluid-wagon'              , --       FluidWagonPrototype               
  'locomotive'               , --       LocomotivePrototype               
  'spider-vehicle'           , --     SpiderVehiclePrototype              
  'wall'                     , --   WallPrototype                         
  'fish'                     , --   FishPrototype                         
  'simple-entity'            , --   SimpleEntityPrototype                 
  'spider-leg'               , --   SpiderLegPrototype                    
  'tree'                     , --   TreePrototype                         
}
